
version: "3"
services:
  nifi:
    image: apache/nifi:1.11.4
    ports:
      - 8083:8083 # Unsecured HTTP Web Port
    environment:
      - NIFI_WEB_HTTP_PORT=8083
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    volumes:
    - ./extensions:/opt/nifi/nifi-current/extensions
